name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  PICO_SDK_PATH: /usr/local/share/pico/pico-sdk
  OPENOCD_PATH: /usr/share/openocd
  PICO_TOOLCHAIN_PATH: /usr/bin

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/source
          submodules: recursive

      - name: Create Build Environment
        working-directory: ${{ github.workspace }}
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B ./build ./source

      - name: Build
        working-directory: ${{ github.workspace }}
        shell: bash
        run: cmake --build ./build --config $BUILD_TYPE --parallel $(nproc)

      - name: Flash
        working-directory: ${{ github.workspace }}/build/test
        shell: bash
        run: openocd -s $OPENOCD_PATH -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c 'adapter speed 5000; program "mytest.elf" verify reset exit'

      - name: Test
        working-directory: ${{ github.workspace }}
        shell: bash
        run: python3 /usr/local/share/pico/unity_checker.py